### ISSUE TITLE
Add support for `xhtml:link rel="alternate"`

### ISSUE THREAD

**Issue by geekdevs** [chemel/sitemap-crawler#1]
This looks like a handy tool. 
Would it be possible to add support for crawling `xhtml:link rel="alternate"` links?
https://support.google.com/webmasters/answer/189077?hl=en

**Comment by chemel** [comment]
Job done ;) See my latest commit : https://github.com/chemel/sitemap-crawler/commit/e8ed5719164d158e72c31217e92a3413b456d0a1

**Comment by geekdevs** [comment]
@chemel awesome, thank you
